# NOTE that the path contained in db_file must be an absolute path
# rlist will create the needed directories
db_file: /home/<your-user>/rlist/rlist.sqlite

# Reference for possible formats: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
datetime_format: ""
